config/routes.rb
ConnectedScholar::Application.routes.draw do
  get "search/keyword"
  get "search/advanced"
  get "search/google"

  resources :documents do
    resources :comments, :only => [:create, :destroy] do
      post 'read', :on => :member
    end
    resources :resources, :only => [:show, :create, :destroy] do
      resources :quotations, :only => [:show, :create, :destroy]
      resources :citations, :only => [:create, :destroy]
      get 'citation', :on => :member
      post 'activate', :on => :member
      member do
        post "default_citation/:citation_id", :action => "promote_citation", :as => :promote_citation
      end
    end
    member do
      get "active_citations", :action => "active_citations", :as => :active_citations
      post "contributors", :action => "add_contributor", :as => :add_contributor
      post "refresh_resources", :action => "refresh_resources", :as => :refresh_resources
      delete "contributors/:contributor_id", :action => "remove_contributor", :as => :remove_contributor
    end
  end

  namespace :admin do
    resources :users, :only => [:index, :destroy] do
      post 'approve', :as => :approve
      post 'promote', :as => :promote
      post 'demote', :as => :demote
    end
  end

  root :to => "dashboard#index"

  devise_for :users,
             :controllers => { :registrations => "registrations" },
             :path_names => { :sign_in => 'sign_in', :sign_out => 'sign_out', :sign_up => "sign_up" } do
    get "users/preferences" => "users#preferences", :as => :user_preferences
    post "users/preferences" => "users#save_preferences", :as => :user_preferences
  end

  match 'pad/'                      => 'pad#index'
  match 'view_pad/:document_id'     => 'pad#view_pad',  :document_id => /[^\/]+/, :as => :view_pad
  match 'pad/pad'                   => 'pad#pad'
  match 'p/:pad_id'                 => 'pad#pad',       :pad_id => /[^\/]+/
  match 'ro/:pad_id'                => 'pad#read_only', :pad_id => /[^\/]+/
  match 'p/:pad_id/export/:type'    => 'pad#export',    :pad_id => /[^\/]+/
  match 'p/:pad_id/timeslider'      => 'pad#timeslider',:pad_id => /[^\/]+/
  match 'ep/pad/connection-diagnostic-info' => 'pad#diagnostic'

  get "help/getting_started"
  get "help/sharing_documents"
  get "help/finding_resources"
  get "help/citing_resources"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @my_documents = Document.my_documents(current_user)
    @shared_documents = Document.find_shared_documents(current_user)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h2>My Documents</h2>
<table class="dashboard_table">
  <% if @my_documents.any? %>
      <tr class="dashboard_divider">
        <td colspan="3"></td>
      </tr>
      <% @my_documents.each do |doc| %>
          <tr>
            <td class="document_name"><%= link_to doc.name, "/view_pad/#{doc.id}" %></td>
            <td class="document_created" id="doc_<%= doc.id %>_date">
              <%= render :inline => set_element_datetime(doc.created_at, "mmm d, yyyy h:MM tt", "doc_#{doc.id}_date") %>
            </td>
            <td class="document_actions"><%= link_to 'Delete', doc, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
          <tr class="dashboard_divider">
            <td colspan="3"></td>
          </tr>
      <% end %>
  <% else %>
      <tr>
        <td class="empty">You have no Documents</td>
      </tr>
  <% end %>
</table>

<p id="new_document_link">
<%= link_to 'New Document', new_document_path %>
</p>

<h2>Shared Documents</h2>
<table class="dashboard_table">
  <% if @shared_documents.any? %>
      <tr class="dashboard_divider">
        <td colspan="3"></td>
      </tr>
      <% @shared_documents.each do |doc| %>
          <tr>
            <td class="document_name"><%= link_to doc.name, "/view_pad/#{doc.id}" %></td>
            <td class="document_owner"><%= doc.owner.name %></td>
            <td class="document_created" id="shareddoc_<%= doc.id %>_date">
              <%= render :inline => set_element_datetime(doc.created_at, "mmm d, yyyy h:MM tt", "shareddoc_#{doc.id}_date") %>
            </td>
          </tr>
          <tr class="dashboard_divider">
            <td colspan="3"></td>
          </tr>
      <% end %>
  <% else %>
      <tr>
        <td class="empty">You have no Shared Documents</td>
      </tr>
  <% end %>
</table>