config/routes.rb
ConnectedScholar::Application.routes.draw do
  get "search/keyword"
  get "search/advanced"
  get "search/google"

  resources :documents do
    resources :comments, :only => [:create, :destroy] do
      post 'read', :on => :member
    end
    resources :resources, :only => [:show, :create, :destroy] do
      resources :quotations, :only => [:show, :create, :destroy]
      resources :citations, :only => [:create, :destroy]
      get 'citation', :on => :member
      post 'activate', :on => :member
      member do
        post "default_citation/:citation_id", :action => "promote_citation", :as => :promote_citation
      end
    end
    member do
      get "active_citations", :action => "active_citations", :as => :active_citations
      post "contributors", :action => "add_contributor", :as => :add_contributor
      post "refresh_resources", :action => "refresh_resources", :as => :refresh_resources
      delete "contributors/:contributor_id", :action => "remove_contributor", :as => :remove_contributor
    end
  end

  namespace :admin do
    resources :users, :only => [:index, :destroy] do
      post 'approve', :as => :approve
      post 'promote', :as => :promote
      post 'demote', :as => :demote
    end
  end

  root :to => "dashboard#index"

  devise_for :users,
             :controllers => { :registrations => "registrations" },
             :path_names => { :sign_in => 'sign_in', :sign_out => 'sign_out', :sign_up => "sign_up" } do
    get "users/preferences" => "users#preferences", :as => :user_preferences
    post "users/preferences" => "users#save_preferences", :as => :user_preferences
  end

  match 'pad/'                      => 'pad#index'
  match 'view_pad/:document_id'     => 'pad#view_pad',  :document_id => /[^\/]+/, :as => :view_pad
  match 'pad/pad'                   => 'pad#pad'
  match 'p/:pad_id'                 => 'pad#pad',       :pad_id => /[^\/]+/
  match 'ro/:pad_id'                => 'pad#read_only', :pad_id => /[^\/]+/
  match 'p/:pad_id/export/:type'    => 'pad#export',    :pad_id => /[^\/]+/
  match 'p/:pad_id/timeslider'      => 'pad#timeslider',:pad_id => /[^\/]+/
  match 'ep/pad/connection-diagnostic-info' => 'pad#diagnostic'

  get "help/getting_started"
  get "help/sharing_documents"
  get "help/finding_resources"
  get "help/citing_resources"
end

app/models/document.rb
class Document < ActiveRecord::Base
  include EtherpadUtil

  CITATION_FORMATS = [['MLA', 'mla'], 
                      ['APA', 'apa'],
                      ['Chicago Author Date', 'chicago-author-date']]


  has_many :comments, :dependent => :destroy
  has_many :resources, :dependent => :destroy

  belongs_to :owner, :class_name => 'User'
  belongs_to :group

  validates_presence_of :name, :etherpad_name

  validates_uniqueness_of :etherpad_name, :scope => :owner_id
  validates_uniqueness_of :name, :scope => :owner_id

  before_create :init_group, :set_etherpad_password, :set_citation_format

  before_validation :set_etherpad_name

  scope :my_documents, lambda {|user| {:conditions => {:owner_id => user.id}}}

  def active_sources
    self.resources.active_sources
  end

  def active_citations
    active_sources.map{|as| as.citations }.flatten.map{|c| {"resource_id" => c.resource_id, "citation_text" => c.citation_text}}
  end

  def recommended_resources
    self.resources.recommended_resources
  end

  def refresh_resources!
    # get the document text
    text = get_pad_text(self)

    resources.each do |r|
      if r.citations.inject(false) {|prev, c| prev || text.include?(c.citation_text) }
        r.activate!
      else
        r.deactivate!
      end
    end
  end
  
  def self.find_shared_documents(user)
    groups = Group.joins(:users).where(:users => {:id => user.id})
    groups.map(&:document)
  end

  def add_contributor_by_email(email)
    if email == owner.email
      yield :cannot_add_owner
    else
      contributor = User.where(:email => email).first
      if contributor.nil?
        yield :unrecognized_email
      else
        unless self.group.users.exists?(:id => contributor.id)
          self.group.users << contributor
        end
        return true
      end
    end
    false
  end

  def remove_contributor(user)
    self.group.users.delete(user)
  end

  def contributors
    group.users
  end

  def etherpad_group_id
    @etherpad_group_id ||= create_group_if_not_exists_for(self)
  end

  def can_be_viewed_by(user)
    self.owner == user || (self.group && self.group.users && self.group.users.include?(user))
  end

  def pad_id
    "#{etherpad_group_id}$#{CGI::escape(etherpad_name)}"
  end

  private

  def init_group
    self.group = Group.create
  end

  def set_citation_format
    self.citation_format =  self.owner ? self.owner.preferences_with_defaults[:citation_format] : 'mla'
  end

  def set_etherpad_password
    self.etherpad_password = SecureRandom.hex(13)
  end

  def set_etherpad_name
    if etherpad_name.nil?
      write_attribute(:etherpad_name, self.name.gsub(' ', '_'))
    else
      if etherpad_name_changed?
        raise "Etherpad name is read-only!"
      end
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    redirect_to root_url
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # _resource.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document].merge(:owner => current_user))

    respond_to do |format|
      if @document.save
        format.html { redirect_to "/view_pad/#{@document.id}", notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_contributor
    email = params[:contributor_email]
    @document = Document.find(params[:id])
    @document.add_contributor_by_email(email) do |error|
      case error
        when :cannot_add_owner
          flash[:alert] = "Cannot add yourself as a contributor"
        when :unrecognized_email
          flash[:alert] = "Could not find user for: #{email}"
      end
    end
    redirect_to @document
  end

  def remove_contributor
    @document = Document.find(params[:id])
    @contributor = User.find(params[:contributor_id])
    @document.remove_contributor(@contributor)
    redirect_to @document
  end

  def refresh_resources
    @document = Document.find(params[:id])
    @document.refresh_resources!
    redirect_to view_pad_path(@document)
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end

  def active_citations
    @document = Document.find(params[:id])
    render :json => @document.active_citations
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
    <% if @document.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@document.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
            <% @document.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :citation_format %>
      <br />
      <%= f.select :citation_format,
                      options_for_select(
                              Document::CITATION_FORMATS, @document.citation_format) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>
<br/>

<%= link_to 'Back', @document %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<style>
    .dashboard_table th {
        text-align: left;
    }

    .dashboard_table .contributor_name {
        max-width: 50px;
    }

    #contributors {
        margin-left: 20px;
        width: 600px
    }
</style>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @document.owner.name %>
</p>

<p>
  <b>Created At:</b>
  <%= @document.created_at %>
</p>

<p>
  <b>Updated At:</b>
  <%= @document.updated_at %>
</p>

<p>
  <b>Contributors:</b>
</p>
<div id="contributors">
  <table class="dashboard_table">
    <% if @document.contributors.empty? %>
        <tr>
          <td class="empty">No Contributors</td>
        </tr>
    <% else %>
        <tr class="dashboard_divider">
          <td colspan="3"></td>
        </tr>
        <% @document.contributors.each do |contributor| %>
            <tr>
              <td class="document_name"><%= contributor.name %></td>
              <td class="document_owner"><%= contributor.email %></td>
              <td class="document_actions"><%= link_to 'Remove', remove_contributor_document_path(@document.id, contributor.id),
                                                       :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
            <tr class="dashboard_divider">
              <td colspan="3"></td>
            </tr>
        <% end %>
    <% end %>
  </table>

  <%= form_tag(add_contributor_document_path(@document.id)) do %>
      <%= text_field_tag :contributor_email, params[:contributor_email], :placeholder => "User Email Address", :size => 40 %>
      <%= submit_tag "Add Contributor" %>
  <% end %>
</div>
<hr/>

<%= link_to 'View Document', view_pad_path(@document) %> | <%= link_to 'Edit Details', edit_document_path(@document) %>