config/routes.rb
ConnectedScholar::Application.routes.draw do
  get "search/keyword"
  get "search/advanced"
  get "search/google"

  resources :documents do
    resources :comments, :only => [:create, :destroy] do
      post 'read', :on => :member
    end
    resources :resources, :only => [:show, :create, :destroy] do
      resources :quotations, :only => [:show, :create, :destroy]
      resources :citations, :only => [:create, :destroy]
      get 'citation', :on => :member
      post 'activate', :on => :member
      member do
        post "default_citation/:citation_id", :action => "promote_citation", :as => :promote_citation
      end
    end
    member do
      get "active_citations", :action => "active_citations", :as => :active_citations
      post "contributors", :action => "add_contributor", :as => :add_contributor
      post "refresh_resources", :action => "refresh_resources", :as => :refresh_resources
      delete "contributors/:contributor_id", :action => "remove_contributor", :as => :remove_contributor
    end
  end

  namespace :admin do
    resources :users, :only => [:index, :destroy] do
      post 'approve', :as => :approve
      post 'promote', :as => :promote
      post 'demote', :as => :demote
    end
  end

  root :to => "dashboard#index"

  devise_for :users,
             :controllers => { :registrations => "registrations" },
             :path_names => { :sign_in => 'sign_in', :sign_out => 'sign_out', :sign_up => "sign_up" } do
    get "users/preferences" => "users#preferences", :as => :user_preferences
    post "users/preferences" => "users#save_preferences", :as => :user_preferences
  end

  match 'pad/'                      => 'pad#index'
  match 'view_pad/:document_id'     => 'pad#view_pad',  :document_id => /[^\/]+/, :as => :view_pad
  match 'pad/pad'                   => 'pad#pad'
  match 'p/:pad_id'                 => 'pad#pad',       :pad_id => /[^\/]+/
  match 'ro/:pad_id'                => 'pad#read_only', :pad_id => /[^\/]+/
  match 'p/:pad_id/export/:type'    => 'pad#export',    :pad_id => /[^\/]+/
  match 'p/:pad_id/timeslider'      => 'pad#timeslider',:pad_id => /[^\/]+/
  match 'ep/pad/connection-diagnostic-info' => 'pad#diagnostic'

  get "help/getting_started"
  get "help/sharing_documents"
  get "help/finding_resources"
  get "help/citing_resources"
end

app/models/user.rb
class User < ActiveRecord::Base
  include EtherpadUtil

  DEFAULT_PREFS = {
      :citation_format => :mla
  }

  serialize :preferences, Hash

  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

  # we can't just call this method :preferences because then changes like u.preferences[:format] = :mla  won't be
  # persisted.
  #
  def preferences_with_defaults
    DEFAULT_PREFS.merge(read_attribute(:preferences) || {})
  end

  def etherpad_author_id
    @etherpad_author_id ||= create_author_if_not_exists_for(self)
  end

  def active_for_authentication?
    approved?
  end

  def inactive_message
    !approved? ? :unapproved : super
  end

  def approve!
    self.approved = true
  end

  def promote!
    self.admin = true
  end

  def demote!
    self.admin = false
  end

  def destroy!
    self.groups.each do |g|
      g.destroy
    end
    Document.destroy_all(:owner_id => self.id)
    self.destroy
  end

  def send_confirmation_instructions
    # nope
  end

  def owns?(doc)
    doc.owner == self 
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end

  def approve
    @user = User.find(params[:user_id])
    authorize! :manage, @user
    @user.approve!
    @user.save!
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html { redirect_to admin_users_path }
    end
  end

  def promote
    @user = User.find(params[:user_id])
    authorize! :manage, @user
    @user.promote!
    @user.save!
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html { redirect_to admin_users_path }
    end
  end

  def demote
    @user = User.find(params[:user_id])
    if @user != current_user
      authorize! :manage, @user
      @user.demote!
      @user.save!
      respond_to do |format|
        format.json { render :json => @user }
        format.xml  { render :xml => @user }
        format.html { redirect_to admin_users_path }
      end
    else
      flash[:alert] = "You cannot remove the Admin role from yourself"
      redirect_to admin_users_path
    end
  end

  # GET /users/1
  # GET /users/1.xml
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  #def show
  #  respond_to do |format|
  #    format.json { render :json => @user }
  #    format.xml  { render :xml => @user }
  #    format.html
  #  end
  #
  #rescue ActiveRecord::RecordNotFound
  #  respond_to_not_found(:json, :xml, :html)
  #end
  #
  ## GET /users/1/edit
  ## GET /users/1/edit.xml
  ## GET /users/1/edit.json                                HTML AND AJAX
  ##-------------------------------------------------------------------
  #def edit
  #  respond_to do |format|
  #    format.json { render :json => @user }
  #    format.xml  { render :xml => @user }
  #    format.html
  #  end
  #
  #rescue ActiveRecord::RecordNotFound
  #  respond_to_not_found(:json, :xml, :html)
  #end

  # DELETE /users/1
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    if @user != current_user
      @user.destroy!

      respond_to do |format|
        format.json { respond_to_destroy(:ajax) }
        format.xml  { head :ok }
        format.html { redirect_to admin_users_path }
      end
    else
      flash[:alert] = "You cannot delete yourself"
      redirect_to admin_users_path
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def save_preferences
    current_user.preferences[:citation_format] = params[:citation_format]
    current_user.save
    redirect_to user_preferences_path
  end
end

app/views/admin/users/index.html.erb
<style>
    .dashboard_table th {
        text-align: left;
    }

    .dashboard_table .action, .date {
        text-align: center;
    }
</style>
<p>
<h2>Pending Users</h2>

<% if @users.any? { |u| !u.approved? } %>
    <table class="dashboard_table">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Created At</th>
        <th></th>
        <th></th>
      </tr>

      <% @users.select { |u| !u.approved? }.each do |u| %>
          <tr>
            <td><%= u.name %></td>
            <td><%= u.email %></td>
            <td><%= u.created_at %></td>
            <td>
              <% unless u.approved? %>
                  <%= link_to 'Approve', admin_user_approve_path(u), :method => :post %>
              <% end %>
            </td>
            <td>
              <% if @user != current_user %>
                  <%= link_to 'Reject', admin_user_path(u), :confirm => 'Are you sure?', :method => :delete %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% else %>
    <span style="font-style: italic">There are no unapproved users</span>
<% end %>
</p>
<hr/>
<p>
<h2>Active Users</h2>
<table class="dashboard_table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Created At</th>
    <th class="action">Admin</th>
    <th></th>
  </tr>

  <% @users.select { |u| u.approved? }.each do |u| %>
      <tr>
        <td><%= u.name %></td>
        <td><%= u.email %></td>
        <td><%= u.created_at %></td>
        <td class="action">
          <% if u.admin? %>
              <% if u != current_user %>
                  <%= link_to 'Remove', admin_user_demote_path(u), :method => :post %>
              <% end %>
          <% else %>
              <%= link_to 'Add', admin_user_promote_path(u), :method => :post %>
          <% end %>
        </td>
        <td class="action">
          <% if u != current_user %>
              <%= link_to 'Delete', admin_user_path(u), :confirm => 'Are you sure?', :method => :delete %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>
</p>