config/routes.rb
ConnectedScholar::Application.routes.draw do
  get "search/keyword"
  get "search/advanced"
  get "search/google"

  resources :documents do
    resources :comments, :only => [:create, :destroy] do
      post 'read', :on => :member
    end
    resources :resources, :only => [:show, :create, :destroy] do
      resources :quotations, :only => [:show, :create, :destroy]
      resources :citations, :only => [:create, :destroy]
      get 'citation', :on => :member
      post 'activate', :on => :member
      member do
        post "default_citation/:citation_id", :action => "promote_citation", :as => :promote_citation
      end
    end
    member do
      get "active_citations", :action => "active_citations", :as => :active_citations
      post "contributors", :action => "add_contributor", :as => :add_contributor
      post "refresh_resources", :action => "refresh_resources", :as => :refresh_resources
      delete "contributors/:contributor_id", :action => "remove_contributor", :as => :remove_contributor
    end
  end

  namespace :admin do
    resources :users, :only => [:index, :destroy] do
      post 'approve', :as => :approve
      post 'promote', :as => :promote
      post 'demote', :as => :demote
    end
  end

  root :to => "dashboard#index"

  devise_for :users,
             :controllers => { :registrations => "registrations" },
             :path_names => { :sign_in => 'sign_in', :sign_out => 'sign_out', :sign_up => "sign_up" } do
    get "users/preferences" => "users#preferences", :as => :user_preferences
    post "users/preferences" => "users#save_preferences", :as => :user_preferences
  end

  match 'pad/'                      => 'pad#index'
  match 'view_pad/:document_id'     => 'pad#view_pad',  :document_id => /[^\/]+/, :as => :view_pad
  match 'pad/pad'                   => 'pad#pad'
  match 'p/:pad_id'                 => 'pad#pad',       :pad_id => /[^\/]+/
  match 'ro/:pad_id'                => 'pad#read_only', :pad_id => /[^\/]+/
  match 'p/:pad_id/export/:type'    => 'pad#export',    :pad_id => /[^\/]+/
  match 'p/:pad_id/timeslider'      => 'pad#timeslider',:pad_id => /[^\/]+/
  match 'ep/pad/connection-diagnostic-info' => 'pad#diagnostic'

  get "help/getting_started"
  get "help/sharing_documents"
  get "help/finding_resources"
  get "help/citing_resources"
end

app/views/layouts/_navigation.html.erb
<div id="leftcol_accordian">
  <% if user_signed_in? %>
      <h3><a href="#">Settings</a></h3>

      <div>
        <%= link_to 'Edit Account', edit_registration_path(current_user) %>
        <br/>
        <%= link_to 'Edit Preferences', user_preferences_path %>
        <br/>
        <% if current_user.admin? %>
            <%= link_to "Manage Users", admin_users_path %>
            <br/>
        <% end %>
      </div>
  <% end %>
  <h3><a href="#">Help</a></h3>

  <div>
    <%= link_to "Getting Started", help_getting_started_path %>
    <br/>
    <%= link_to "Sharing Documents", help_sharing_documents_path %>
    <br/>
    <%= link_to "Finding Resources", help_finding_resources_path %>
    <br/>
    <%= link_to "Citing Resources", help_citing_resources_path %>
    <br/>
  </div>
</div>

app/views/layouts/_top.html.erb
<style>
</style>


<div id="top">
  <div class="location">
    <%= link_to "Dashboard", documents_path %>
  </div>
  <div class="logo">
    <img src="/static/img/logo_white.png">
  </div>
  <div class="user_actions">
    <% if user_signed_in? %>
        Hi, <%= current_user.name %>
        |
        <%= link_to 'Account', edit_registration_path(current_user) %>
        |
        <%= link_to 'Help', help_getting_started_path %>
        |
        <%= link_to('Logout', destroy_user_session_path) %>
    <% else %>
        <%= link_to('Sign Up', new_user_registration_path) %>
        |
        <%= link_to('Login', new_user_session_path) %>
    <% end %>
  </div>
</div>
<div class="topDivider"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectedScholar</title>
  <%= yield :head %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="/js/date.format.js"></script>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "/static/css/custom-theme1/jquery-ui-1.8.16.custom.css" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
      jQuery(document).ready(function() {
          $("#leftcol_accordian").accordion({
              collapsible: false
          });
      });
  </script>
</head>
<body>
<%= render :partial => 'layouts/top' %>
<div id="mainContent">
  <div class="leftcol">
    <%= render :partial => 'layouts/navigation' %>
  </div>
  <div class="primary">
    <%= render :inline => flash_helper %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/pad.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectedScholar</title>
  <%= yield :head %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "/static/css/custom-theme1/jquery-ui-1.8.16.custom.css" %>
  <%= csrf_meta_tags %>
  <script>
      $(window).resize(function() {
          resizeDivs();
      });
      $(window).load(function() {
          resizeDivs();
      });

      function resizeDivs() {
          // TODO determine if other accordions are collapsed.  And adjust height accordingly?
          $('#commentsAccordion .ui-accordion-content').height($(window).height().toString() - 400);
          $('#sourcesAccordion .ui-accordion-content').height($(window).height().toString() - 255);
      }
  </script>
  <style>
      * {
          overflow: hidden;
      }

      a.recommended_resource {

      }

      a.active_source {
          color: #993300;
      }

      #activeLegend {
          display: inline-block;
          height: 10px;
          width: 10px;
          min-height: 10px;
          min-width: 10px;
          border: #000000;
          background-color: #993300;
      }

      #inactiveLegend {
          display: inline-block;
          height: 10px;
          width: 10px;
          min-height: 10px;
          min-width: 10px;
          border: #000000;
          background-color: #000000;
      }

      #padLeft, #padRight {
          height: 100%;
          width: 20%;
          background-color: #E1E8E8;
          overflow: auto;
      }

      #padMiddle {
          width: 60%;
      }

      #borderContainer, #leftRightContainer {
          height: 100%;
      }

      #chaticon, #editorcontainerbox, #chatbox {
          bottom: 45px;
      }

      .padAccordion {
          margin: 10px;
          width: auto;
      }

      .padAccordion .ui-accordion-content {
          padding-left: 15px;
          padding-right: 30px;
      }

      #detailsAccordion p {
          margin-bottom: 5px;
      }

      #detailsAccordion .ui-accordion-content {
          height: 190px;
      }

      #searchAccordion .ui-accordion-content {
          height: 50px;
      }

      #sourcesAccordion .ui-accordion-content {
          height: 2000px; /* just a place holder until the js resizes me */
          overflow-y: auto;
          padding-left: 0;
          padding-right: 0;
      }

      #commentsAccordion .ui-accordion-content {
          height: 2000px; /* just a place holder until the js resizes me */
          overflow-y: auto;
      }

      #commentsAccordion .comment_item {
          clear: both;
          margin: 0 0 5px 0;
      }

      #commentsAccordion .unread {
          background-color: #E0EEEE;
      }

      #commentsAccordion .comment_divider {
          margin-bottom: 15px;
      }

      #commentsAccordion .comment_date {
          width: auto;
          float: left;
          color: #999999;
      }

      #commentsAccordion .comment_delete {
          width: 16px;
          float: right;
      }

      #commentsAccordion .comment_text {
          margin: 0 0 5px 10px
      }

      #commentsAccordion .comment_header {
          margin-bottom: 5px;
      }

      #commentsAccordion .comment_author {
          color: #777777;
          font-style: italic;
      }

      #sourcesAccordion .resource_item {
          font-size: 10pt;
      }

      #sourcesAccordion .resource_quote {
          margin-top: 7px;
          margin-bottom: 7px;
      }

      .resource-legend {
          color: #888888;
      }

      .resource-legend a:hover {
          color: #388EB4;
      }

      #sourcesAccordion .resource_item, .resource-legend {
          margin-left: 24px;
          margin-right: 24px;
      }

      #searchAccordion .ui-accordion-header {
          background: #839668;
      }

      #sourcesAccordion .ui-accordion-header {
          background: #BA745C;
      }

      .ui-tabs .ui-tabs-selected.ui-state-active.ui-state-default.ui-corner-top {
          background-color: #F2F7F7;
          background-image: none;
          border-bottom: none;
      }

      .ui-tabs .ui-tabs-selected.ui-state-active.ui-state-default.ui-corner-top a {
          color: black;
      }

  </style>
</head>
<body>
<%= render :partial => 'layouts/top' %>
<div id="main">
  <div id="mainContent">
    <%= yield %>
  </div>
</div>

</body>
</html>